defaults:
  - trainer
  - override trainer/callbacks: default_teacher_student
  - _self_

encoder:
  teacher: ???
  student: ???
model:
  _target_: aligner.teacher_student.TeacherStudentLightningModule
trainer:
  benchmark: true
  deterministic: false
  devices: -1
  replace_sampler_ddp: false
  val_check_interval: 0.02
